name = "aesop_with_overrides"
defaultTargets = ["AesopWithOverrides"]

[[require]]
name = "mathlib"
path = "../NeuralTactic/.lake/packages/mathlib"

[[lean_lib]]
name = "AesopWithOverrides"

[[lean_lib]]
name = "Examples"
globs = ["Examples.+"]
leanOptions = {linter.unusedVariables = false}
