// AUTO-GENERATED by scripts/train.py
// Deep Sets linear ranker: score(goal, cand) = dot(W_GOAL, bow(goal)) + dot(W_CAND, bow(cand))
// Operates on raw text (C-strings); no Lean serialization needed.
#include <lean/lean.h>
#include <cstring>
#include <cctype>
#include <string>
#include <sstream>
#include <vector>

static const int VOCAB_SIZE = 16;
static const char* VOCAB[16] = { "!", "&", "(", ")", "=", "a", "b", "c", "else", "false", "if", "p", "q", "then", "true", "|" };
static const double W_GOAL[16] = { -4.00775333059266714e-16, -1.35544990487700134e-14, -1.46768448089362735e-14, -1.46768448089362735e-14, -1.20910768376669697e-14, -1.46768448089362735e-14, -1.46768448089362735e-14, 4.90075644996035287e-15, -4.73037407855425585e-15, -6.77724952438500672e-15, -4.73037407855425585e-15, 0.00000000000000000e+00, 0.00000000000000000e+00, -4.73037407855425585e-15, -7.79714834364675369e-15, -5.96459595039386392e-15 };
static const double W_CAND[16] = { 5.10883874520872983e+00, 0.00000000000000000e+00, 1.50382602649218322e+00, 1.50382602649218322e+00, -4.80668362495537238e+00, -1.20167090623886486e+00, -1.20167090623886486e+00, 2.45037822498017643e-15, -7.33842240446813676e-15, -2.40334181247771150e+00, -7.33842240446813676e-15, 0.00000000000000000e+00, 0.00000000000000000e+00, -7.33842240446813676e-15, -1.20167090623886352e+00, 0.00000000000000000e+00 };

static std::vector<std::string> tokenize(const char* text) {
    std::vector<std::string> tokens;
    std::string tok;
    for (const char* p = text; *p; p++) {
        if (std::isalpha((unsigned char)*p) || std::isdigit((unsigned char)*p)) {
            tok += *p;
        } else {
            if (!tok.empty()) { tokens.push_back(tok); tok.clear(); }
            if (!std::isspace((unsigned char)*p)) tokens.push_back(std::string(1, *p));
        }
    }
    if (!tok.empty()) tokens.push_back(tok);
    return tokens;
}

static double bow_dot(const char* text, const double* weights) {
    auto tokens = tokenize(text);
    double score = 0.0;
    for (int v = 0; v < VOCAB_SIZE; v++) {
        double count = 0.0;
        for (auto& t : tokens) if (t == VOCAB[v]) count += 1.0;
        score += weights[v] * count;
    }
    return score;
}

// Lean FFI: goal_str and cand_str are Lean Strings.
// Returns the ranking score as a double.
LEAN_EXPORT double lean_neural_score(lean_object* goal_str, lean_object* cand_str) {
    const char* goal = lean_string_cstr(goal_str);
    const char* cand = lean_string_cstr(cand_str);
    return bow_dot(goal, W_GOAL) + bow_dot(cand, W_CAND);
}
