#!/usr/bin/env bash
# Build the Lean FFI native libraries.
#
# Produces two libraries:
#   native/libclient.a  — socket client (score_client.c); links with neural_grind
#   native/libmodel.a   — embedded weights (model.cpp, generated by train.py);
#                         alternative to the server for compiled deployment
#
# Run after scripts/train.py has generated native/model.cpp.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LEAN_PREFIX="$(lean --print-prefix)"

echo "Lean prefix: $LEAN_PREFIX"

echo "Building native/score_client.c..."
gcc -O2 -c "$ROOT/native/score_client.c" \
    -I"$LEAN_PREFIX/include" \
    -o "$ROOT/native/score_client.o"
ar rcs "$ROOT/native/libclient.a" "$ROOT/native/score_client.o"
echo "Built $ROOT/native/libclient.a"

echo "Building native/model.cpp..."
g++ -O2 -std=c++17 \
    -c "$ROOT/native/model.cpp" \
    -I"$LEAN_PREFIX/include" \
    -o "$ROOT/native/model.o"
ar rcs "$ROOT/native/libmodel.a" "$ROOT/native/model.o"
echo "Built $ROOT/native/libmodel.a"
