/-
`NeuralTactic.CollectTactic` — the `neural_collect` tactic.

Like `neural_grind`, but implemented entirely in pure Lean (no `@[extern]`),
so it works correctly under `lake env lean` (the Lean interpreter).

Key features compared to `neural_grind` / `NeuralTactic.Tactic`:
  • Scoring uses a pure Lean heuristic by default (prefer input splits, fewer cases).
  • When `$GRIND_MODEL` and `$GRIND_SERVE` are both set, the tactic spawns
    `serve.py` as a persistent subprocess and queries it for model scores.
    The subprocess is kept alive across multiple proofs in a batch.
  • Every split decision is logged to `$GRIND_LOG` (JSONL format).
  • The tactic is named `neural_collect` to avoid conflicting with `neural_grind`.

Environment variables:
  GRIND_LOG   — path to the JSONL log file (required for data collection)
  GRIND_MODEL — path to the PyTorch model checkpoint (.pt)
  GRIND_SERVE — path to training/serve.py (required when GRIND_MODEL is set)

Use `neural_collect` inside batch `.lean` files generated by `training/collect.py`.
-/
import Lean.Elab.Tactic.Basic
import Lean.Meta.Tactic.Grind.Main
import Lean.Meta.Tactic.Grind.Finish
import Lean.Meta.Tactic.Grind.EMatchAction
import Lean.Meta.Tactic.Grind.Intro
import NeuralTactic.LoggingV2

open Lean Meta Elab Tactic Grind

namespace NeuralTactic

-- ---------------------------------------------------------------------------
-- Source tag (mirrors `SOURCE_TAGS` in training/features.py)
-- ---------------------------------------------------------------------------

private def sourceTagStr (si : SplitInfo) : String :=
  match si.source with
  | .ematch _     => "ematch"
  | .ext _        => "ext"
  | .mbtc _ _ _   => "mbtc"
  | .beta _       => "beta"
  | .forallProp _ => "forallProp"
  | .existsProp _ => "existsProp"
  | .input        => "input"
  | .inj _        => "inj"
  | .guard _      => "guard"

-- ---------------------------------------------------------------------------
-- Heuristic scoring (pure Lean, no @[extern])
-- ---------------------------------------------------------------------------

-- Higher score = preferred.  Prefer: input > ematch > inj > ext > others;
-- fewer numCases; shorter expression text.
private def heuristicScore (cand : SplitCandidateWithAnchor) (exprLen : Nat) : Float :=
  let srcPri : Float :=
    match cand.c.source with
    | .input        => 100.0
    | .ematch _     => 80.0
    | .inj _        => 70.0
    | .guard _      => 60.0
    | .ext _        => 50.0
    | .mbtc _ _ _   => 40.0
    | .beta _       => 30.0
    | .forallProp _ => 20.0
    | .existsProp _ => 10.0
  srcPri - cand.numCases.toFloat * 10.0 - exprLen.toFloat * 0.01

-- ---------------------------------------------------------------------------
-- Optional model server (persistent subprocess, lazy-initialized)
-- ---------------------------------------------------------------------------

private structure ModelServer where
  stdinH  : IO.FS.Handle
  stdoutH : IO.FS.Handle

private initialize modelServerRef  : IO.Ref (Option ModelServer) ← IO.mkRef none
private initialize modelServerPath : IO.Ref String               ← IO.mkRef ""

/-- Return the model server (starting it if necessary), or `none` when env vars are absent. -/
private def getOrStartModelServer : IO (Option ModelServer) := do
  let some modelPath ← IO.getEnv "GRIND_MODEL" | return none
  let some servePath ← IO.getEnv "GRIND_SERVE" | return none
  let pythonBin ← do
    match ← IO.getEnv "GRIND_PYTHON" with
    | some p => pure p
    | none   => pure "python3"
  -- Reuse existing server when the model path hasn't changed
  let currPath ← modelServerPath.get
  if currPath == modelPath then
    if let some h := ← modelServerRef.get then return some h
  -- Spawn a new server
  try
    let child ← IO.Process.spawn {
      cmd    := pythonBin,
      args   := #[servePath, "--model", modelPath],
      stdin  := .piped,
      stdout := .piped,
      stderr := .inherit,
    }
    let srv : ModelServer := { stdinH := child.stdin, stdoutH := child.stdout }
    modelServerRef.set (some srv)
    modelServerPath.set modelPath
    return some srv
  catch _ => return none

/--
Send a decision query to serve.py and return the chosen anchor.
Sends goalFeatures, candidates (with generation), statePP, and grindState.
Returns 0 on error (caller falls back to heuristic).
-/
private def queryModelServer (gfJson : String) (candsJson : String)
    (statePPJson : String) (grindStateJson : String) : IO UInt64 := do
  let some srv ← getOrStartModelServer | return 0
  try
    let query :=
      "{\"goalFeatures\":"  ++ gfJson       ++
      ",\"candidates\":"    ++ candsJson    ++
      ",\"statePP\":"       ++ statePPJson  ++
      ",\"grindState\":"    ++ grindStateJson ++ "}\n"
    srv.stdinH.putStr query
    srv.stdinH.flush
    let line ← srv.stdoutH.getLine
    let digits := String.ofList (line.toList.filter (·.isDigit))
    match digits.toNat? with
    | some n => return UInt64.ofNat n
    | none   => return 0
  catch _ =>
    modelServerRef.set none
    return 0

-- Grind trace classes whose events we accumulate as grindState context
private def GRIND_STATE_CLASSES : List Name :=
  [`grind.assert, `grind.eqc, `grind.ematch.instance.assignment]

-- ---------------------------------------------------------------------------
-- The split action with logging
-- ---------------------------------------------------------------------------

private def collectSplitNext (proofSnapStart : Nat)
    (stopAtFirstFailure := true) (compress := true) : Action :=
  fun goal kna kp => do
    let (anchors, goal') ← GoalM.run goal getSplitCandidateAnchors
    if anchors.candidates.isEmpty then
      kna goal'
    else
      -- Pretty-print all candidate expressions
      let candPPs ← anchors.candidates.mapM fun c =>
        Format.pretty <$> ppExpr c.e

      -- goalFeatures JSON
      let splitDepth   := goal'.split.num
      let assertedCnt  := goal'.facts.size
      let ematchRounds := goal'.ematch.num
      let traceLen     := goal'.split.trace.length
      let numCands     := anchors.candidates.size
      let gfJson :=
        "{\"splitDepth\":"    ++ toString splitDepth   ++
        ",\"assertedCount\":" ++ toString assertedCnt  ++
        ",\"ematchRounds\":"  ++ toString ematchRounds ++
        ",\"splitTraceLen\":" ++ toString traceLen     ++
        ",\"numCandidates\":" ++ toString numCands     ++ "}"

      -- candidates JSON — now includes generation
      let candJsons ← (anchors.candidates.zip candPPs).mapM fun (c, pp) => do
        let gen := goal'.getGeneration c.e
        let j :=
          "{\"anchor\":"     ++ toString c.anchor                     ++
          ",\"exprText\":"   ++ jsonStr pp                            ++
          ",\"numCases\":"   ++ toString c.numCases                   ++
          ",\"isRec\":"      ++ (if c.isRec then "true" else "false") ++
          ",\"source\":"     ++ jsonStr (sourceTagStr c.c)            ++
          ",\"generation\":" ++ toString gen                          ++ "}"
        return j
      let candsArr := "[" ++ ",".intercalate candJsons.toList ++ "]"

      -- statePP: local hypotheses + goal (what the infoview shows)
      let decl ← goal'.mvarId.getDecl
      let hyps ← decl.lctx.foldlM (init := #[]) fun acc d => do
        if d.isImplementationDetail then return acc
        let tp := Format.pretty (← ppExpr d.type)
        return acc.push (jsonStr s!"{d.userName} : {tp}")
      let goalTP := Format.pretty (← ppExpr (← goal'.mvarId.getType))
      let statePPArr := hyps.push (jsonStr s!"⊢ {goalTP}")
      let statePPJson := "[" ++ ",".intercalate statePPArr.toList ++ "]"

      -- grindState: grind.assert / grind.eqc / grind.ematch events since proof start
      let allTraces := (← getTraceState).traces
      let grindEvts ← (allTraces.toArray.extract proofSnapStart allTraces.size).foldlM
        (init := #[]) fun acc elem => do
          match elem.msg with
          | .trace data inner _ =>
            if GRIND_STATE_CLASSES.contains data.cls then
              return acc.push (jsonStr (Format.pretty (← inner.format)))
            else return acc
          | _ => return acc
      let grindStateJson := "[" ++ ",".intercalate grindEvts.toList ++ "]"

      -- Try model server; fall back to heuristic
      let modelAnchor ← queryModelServer gfJson candsArr statePPJson grindStateJson
      let modelCand? : Option SplitCandidateWithAnchor :=
        if modelAnchor != 0 then anchors.candidates.find? (·.anchor == modelAnchor)
        else none

      -- Heuristic argmax (loop avoids needing Inhabited instance)
      let mut hBest : Option (SplitCandidateWithAnchor × Float) := none
      for (c, pp) in anchors.candidates.zip candPPs do
        let s := heuristicScore c pp.length
        match hBest with
        | none         => hBest := some (c, s)
        | some (_, bs) => if s > bs then hBest := some (c, s)

      let some bestCand :=
          modelCand?.orElse (fun _ => hBest.map Prod.fst) | kna goal'

      -- Log this step (rich schema matching grind_collect output)
      let stepIdx ← nextStepIdxV2
      let stepJson :=
        "{\"step\":"          ++ toString stepIdx        ++
        ",\"goalFeatures\":"  ++ gfJson                  ++
        ",\"statePP\":"       ++ statePPJson              ++
        ",\"grindState\":"    ++ grindStateJson           ++
        ",\"candidates\":"    ++ candsArr                ++
        ",\"chosenAnchor\":"  ++ toString bestCand.anchor ++ "}"
      appendStepV2 stepJson

      -- Perform the split
      let gen    := goal'.getGeneration bestCand.e
      let genNew := if bestCand.numCases > 1 || bestCand.isRec then gen + 1 else gen
      let step   :=
        Action.splitCore bestCand.c bestCand.numCases bestCand.isRec
                         stopAtFirstFailure compress >>
        Action.intros genNew >>
        Action.assertAll
      step goal' kna kp

-- ---------------------------------------------------------------------------
-- Action loop (mirrors mkNeuralFinish / mkFinish)
-- ---------------------------------------------------------------------------

private def mkCollectFinish (proofSnapStart : Nat)
    (maxIterations : Nat := Action.maxIterationsDefault) : IO Action := do
  let solvers ← Solvers.mkAction
  let step : Action :=
    solvers <|> Action.instantiate <|> collectSplitNext proofSnapStart <|> Action.mbtc
  return Action.checkTactic (warnOnly := true) >>
         Action.intros 0 >>
         Action.assertAll >>
         step.loop maxIterations

-- ---------------------------------------------------------------------------
-- Per-goal runner (mirrors neuralMain in Tactic.lean)
-- ---------------------------------------------------------------------------

private def collectMain (mvarId : MVarId) (params : Params)
    (proofSnapStart : Nat) : MetaM Result :=
  GrindM.runAtGoal mvarId params fun goal => do
    let finish ← mkCollectFinish proofSnapStart
    let failure? ← match (← finish.run goal) with
      | .closed _       => pure none
      | .stuck (g :: _) => pure (some g)
      | .stuck []       => pure none
    mkResult params failure?

-- ---------------------------------------------------------------------------
-- `neural_collect` tactic
-- ---------------------------------------------------------------------------

syntax (name := neuralCollect) "neural_collect" : tactic

/--
`neural_collect` runs grind with a pure-Lean scorer and logs every split
decision to `$GRIND_LOG` (JSONL).

When `$GRIND_MODEL` and `$GRIND_SERVE` are set, decisions are delegated to
the Python model server (serve.py) for model-guided exploration; otherwise
the heuristic (prefer input splits, fewer cases) is used.

Use inside batch `.lean` files generated by `training/collect.py`.
-/
@[tactic neuralCollect]
def evalNeuralCollect : Tactic := fun _ => do
  let mvarId ← getMainGoal
  let config : Grind.Config := {}
  let params ← Grind.mkDefaultParams config

  -- Use the mvar name as a cheap proof identifier
  let proofId : UInt64 := hash mvarId.name

  -- Reset step log for this proof
  initProofLogV2

  -- Enable grind state trace classes and snapshot trace index before proof starts
  -- so collectSplitNext can accumulate grind.assert / grind.eqc events.
  let proofSnapStart := (← getTraceState).traces.size

  -- Run the proof, record outcome, flush log
  withOptions (fun opts =>
    GRIND_STATE_CLASSES.foldl (fun o cls => o.setBool (`trace ++ cls) true) opts
  ) do
    withProtectedMCtx config mvarId fun mvarId' => do
      let result ← collectMain mvarId' params proofSnapStart
      let outcome := if result.hasFailed then "failure" else "success"
      flushProofLogV2 proofId outcome
      if result.hasFailed then
        throwError "`neural_collect` failed\n{← result.toMessageData}"
      replaceMainGoal []

end NeuralTactic
